### ISSUE TITLE
Craft tracking

### ISSUE THREAD

**Issue by laytya** [teelolws/Altoholic-Classic#39]
not working craft list of alts. just not showing any recipte....
tryed delete - rescan - import

![Скриншот 2020-06-08 10 48 54](https://user-images.githubusercontent.com/20452393/83991280-75741b80-a976-11ea-849d-704c2883db6f.png)

this is alt on another account

on another alt - showing online alt's crafts insted of imported crafts of another alt

**Comment by teelolws** [comment]
Can you upload your Datastore_Crafts saved variables: 
![image](https://user-images.githubusercontent.com/49792789/83992071-1d9fd980-a9a3-11ea-9fd5-4ac24b278a96.png)

**Comment by laytya** [comment]
how can i send it to you?

**Comment by teelolws** [comment]
Upload it here. 
![image](https://user-images.githubusercontent.com/49792789/83996133-783f3280-a9af-11ea-8aad-3f0ca18eb66d.png)

**Comment by laytya** [comment]
https://pastebin.com/kjfntFsZ

could not upload here - look at pastebin

**Comment by teelolws** [comment]
Okay, so the problem is the account you are sending to doesn't have the entire "reference database", so it has no database to get icons and item details from. When I first tested account sharing, I was sending a small database to a large database, so I never noticed the issue.

What I will need to do is add to account sharing. I will need to get it to also send the Datastore_Crafts ReferenceDB table, too. This table is large, and will slow the data transfer considerably. Especially if you're sending the data from an account that has every profession maxed out.

The account sharing code is complicated and I don't truly understand it. It will take me some time to change it.

If you want to do a workaround in the meantime, open the DataStore_Crafts saved variables of the account you're sending from, and copy/paste the entire DataStore_CraftsRefDB->global section to replace the one on your other account:
![image](https://user-images.githubusercontent.com/49792789/84105352-24deea00-aa6c-11ea-8863-4af0ca352110.png)

**Comment by teelolws** [comment]
Fix uploaded to curseforge: https://www.curseforge.com/wow/addons/altoholic-classic/files/2978999

I haven't been able to extensively test this, as I don't have two accounts. After updating the addon, you will need to log into your characters and open their profession spellbooks to re-populate the database.
