### ISSUE TITLE
Error in account sharing (professions) - Sending char

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#53]
On the sending char, I got the error below when I accept the sharing request.
I then disabled "Professions" in Shared Content and the request was processed.

SENDING CHAR:
Date: 2020-08-07 17:54:06
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua line 941:
   attempt to index local 'craftTable' (a number value)
Debug:
   [C]: ?
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:941:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:905
   (tail call): ?
   Altoholic\Frames\AccountSharing.lua:446: GetSourceTOC()
   Altoholic\Comm.lua:286: SendSourceTOC()
   Altoholic\Comm.lua:241: onClickCallback()
   Altoholic\Frames\MessageBox.lua:18: Button_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:

**Comment by teelolws** [comment]
You have data from a character you haven't logged into for a long time. Can you log into each of your characters and open their profession windows? That includes Cooking and First Aid if the character has them.

I had to change the way DataStore_Crafts stores professions on Classic, because there were issues with using the Retail method. Wrong recipes, wrong reagents, and such. I did a small write up when I made the change: https://github.com/teelolws/Altoholic-Classic/wiki/Account-Sharing-Notes
