### ISSUE TITLE
raid lockouts

### ISSUE THREAD

**Issue by shawndalton** [teelolws/Altoholic-Classic#54]
hate to ask for something new, but any plans to add this?

**Comment by teelolws** [comment]
It went poof when I removed Datastore_Agenda, as it was entirely calendar based. I'll add it to my list.

**Comment by teelolws** [comment]
Done: https://github.com/teelolws/Altoholic-Classic/compare/e5d933f08f07...cf83de171210

I had to recreate some of Blizzards C_Calendar functions since they don't exist in Classic. Things like detecting leap years, detecting how many days in the month, what is the first day of the month, etc. It'll stop working correctly in 2052. Tell whoever takes over the addon to switch it to a proper leap year function.
