### ISSUE TITLE
Formula: Enchant Weapon - Demonslaying

### ISSUE THREAD

**Issue by Ev3ryb0dy** [teelolws/Altoholic-Classic#56]
Title's recipe is wrongfully seen as a (300) Enchant required, but it is really a (230), so I see the formula as a "Could be learned" when its already known.
Small issue but I bought it for nothing :')

<img width="541" alt="Capture d’écran 2020-08-14 à 15 27 23" src="https://user-images.githubusercontent.com/40971508/90254254-bf7bf080-de42-11ea-9a19-2f562f0d9f3d.png">

**Comment by teelolws** [comment]
Looks like we've found another French Blizzard translation oddity. In the spellbook it says "demons" but the recipe just says "demon".

![image](https://user-images.githubusercontent.com/49792789/90294067-aa9e6c00-ded9-11ea-8d7e-d53e06426042.png)

It also shortens "Enchantement" to "Ench."

I tested other recipes, same problem:

![image](https://user-images.githubusercontent.com/49792789/90294305-31ebdf80-deda-11ea-9ecc-3aee75969c91.png)

Altoholic uses a strict name comparison. Blizzard didn't give me any other way to check if your character knows the recipe.

Fixed in: https://github.com/teelolws/Altoholic-Classic/commit/8657b34d2f8dde85d44d52747ee67e6fe0044b03
