### ISSUE TITLE
Known Recipes: Switching a category in the default crafting UI causes known recipes to only include those in that category

### ISSUE THREAD

**Issue by Nazgutek** [teelolws/Altoholic-Classic#71]
The following screen shots are from a Hunter character who is the set to show in the first column of the Grids.

Selecting All Subclasses:

![image](https://user-images.githubusercontent.com/50041970/94345816-8b3e4700-0020-11eb-8fcf-ca2979638480.png)

After refreshing the grid window, results in the first column showing what this character knows:

![image](https://user-images.githubusercontent.com/50041970/94345827-9ee9ad80-0020-11eb-8410-09513a173dc9.png)

If I then select Explosives in the crafting window:

![image](https://user-images.githubusercontent.com/50041970/94345844-b5900480-0020-11eb-8f63-4209b1aaa61e.png)

Without closing the Engineering crafting window, refreshing the grids shows only Explosives being known:

![image](https://user-images.githubusercontent.com/50041970/94345873-e112ef00-0020-11eb-820f-d199b334cd97.png)

If I then select Parts:

![image](https://user-images.githubusercontent.com/50041970/94345881-ef610b00-0020-11eb-8dbb-d599de74216d.png)

The grids will show only items belonging to the Parts category:

![image](https://user-images.githubusercontent.com/50041970/94345888-f9830980-0020-11eb-8aa3-2c33a6a583b8.png)

(Grid is refreshed by selecting 'Keyring', then back to 'Trade Skills')

**Comment by teelolws** [comment]
Congrats, I think you're the only person who has ever used those filter buttons! I certainly never considered testing them.

Fixed in: https://github.com/teelolws/Altoholic-Classic/commit/1f8be433584a379e9af01ae03b52c3532b66b924

One side-effect of this fix, though: if you learn a new recipe while you have a filter selected, Altoholic won't track that new recipe until you remove the filter. Theres nothing I can do about this.

**Comment by Nazgutek** [comment]
Yeah, I thought you'd end up with some issue around the filters blocking what recipes are known :)

Again, thank you for all your excellent work on this addon, it's superb!
