### ISSUE TITLE
LUA error regarding recipes

### ISSUE THREAD

**Issue by Painstormx** [teelolws/Altoholic-Classic#73]
I'm beginning to get the error below on/off when looking at recipes.
It's not consistent at all.
However, right now I got one way of reproduce it:
I go to the AH, select Recipes and search for "undeath".
Whenever one of these recipes show up in the window, I get the error as soon as they are found.
Don't know if it's related to alts knowing the recipes or not.

Date: 2020-09-29 07:27:59
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Altoholic\Tooltip.lua line 314:
   bad argument #1 to 'lower' (string expected, got nil)
Debug:
   [C]: lower()
   Altoholic\Tooltip.lua:314: callback()
   ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:742:
      ...terface\AddOns\DataStore_Crafts\DataStore_Crafts.lua:720
   (tail call): ?
   Altoholic\Tooltip.lua:295: GetRecipeOwners()
   Altoholic\Altoholic.lua:190: AuctionFrameBrowse_Update()
   ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:277:
      ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:275
Locals:
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by teelolws** [comment]
Looks like I introduced an error when I was fixing that transmute recipe bug!

Fixed in: https://github.com/teelolws/Altoholic-Classic/compare/e4a806ff7ed3...038ecee604d2

BUT: sometimes transmute recipes won't show if they're learned or not learned properly the first time you check, if you've never looted the item before. Especially problematic on the auction house.
